## Main front-end
http://staging.traefik.me/
## Wildcards && custom domain =>> http://***.**

## Containers registry
https://registry.traefik.me/

## GraphQl federation proxy
http://staging.traefik.me/graphql/

## Object store proxy
http://staging.traefik.me/service/storage/
http://storage.traefik.me/

## Navigation routing proxy
http://staging.traefik.me/service/routing/

## Geocoding proxy
http://staging.traefik.me/service/geocoding/

## Tracking data ingest proxy
http://staging.traefik.me/service/movement/

## Docs and support platform front-end
http://support.traefik.me/

## Main management front-end
http://manage.traefik.me/

## Proxy administration UI
http://manage.traefik.me/proxy/

## Data administration UI
http://manage.traefik.me/data-admin/

## Management GraphQl proxy/front-end
http://manage.traefik.me/graphql/

## Object store management UI
http://manage-storage.traefik.me/

## Traccar management UI
http://manage-iot.traefik.me/
