export enum FieldType {
  TEXT = 'text',
  NUMBER = 'number',
  DATE = 'date',
  TIME = 'time',
  DATETIME = 'datetime',
  SELECT = 'select',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  SLIDER = 'slider',
  TEXTAREA = 'textarea',
  FILE = 'file',
  IMAGE = 'image',
  PASSWORD = 'password',
  HIDDEN = 'hidden',
  RATING = 'rating',
  MULTISELECT = 'multiselect',
  MULTICHECKBOX = 'multicheckbox',
}
