// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CorePageWrapper: typeof import('./src/shared/components/CorePageWrapper.vue')['default']
    ErrorPageWrapper: typeof import('./src/shared/pages/ErrorPageWrapper.vue')['default']
    LayoutWrapper: typeof import('./src/shared/layouts/components/LayoutWrapper.vue')['default']
    LoadingIndicator: typeof import('./src/shared/layouts/components/LoadingIndicator.vue')['default']
    PageWrapper: typeof import('./src/shared/pages/PageWrapper.vue')['default']
  }
}

export { }
