export enum VehicleType {
  BICYCLE = 'bicycle',
  BUS = 'bus',
  CAR = 'car',
  CRANE = 'crane',
  MOTOCYCLE = 'motorcycle',
  OFFROAD = 'offroad',
  PERSON = 'person',
  PICKUP = 'pickup',
  TRACTOR = 'tractor',
  TRAIN = 'train',
  TROLLEYBUS = 'trolleybus',
  TRUCK = 'truck',
  VAN = 'van',
  SCOOTER = 'scooter',
}
